
export enum AppStep {
  ONBOARDING = 'ONBOARDING',
  DASHBOARD = 'DASHBOARD',
  STUDIO = 'STUDIO',
  GALLERY = 'GALLERY',
  AI_CREATOR = 'AI_CREATOR',
}

export interface EntityProfile {
  id: string;
  name: string;
  description: string; // Generated by Gemini
  images: string[]; // Base64
  type: 'PERSON' | 'PRODUCT';
  isAI?: boolean; // Flag to identify generated personas
}

export interface AppState {
  people: EntityProfile[]; // List of available models (User + AI)
  products: EntityProfile[];
  gallery: GeneratedImage[];
  likedPrompts: string[]; // "Memory" of what the user likes
}

export enum GenerationMode {
  USER_ONLY = 'USER_ONLY',
  PRODUCT_ONLY = 'PRODUCT_ONLY',
  COMBINED = 'COMBINED',
}

export interface GeneratedImage {
  id: string;
  url: string;
  prompt: string;
  mode: GenerationMode;
  productId?: string; // Which product was used
  personId?: string; // Which person was used
  styleId?: string; // The style used
  timestamp: number;
  feedback?: 'like' | 'dislike';
  parentId?: string; // If derived from another image (edit/export)
}

export interface TrainingData {
  userImages: string[];
  userDescription: string;
  productImages: string[];
  productDescription: string;
  userName: string;
  productName: string;
}

export interface ArtStyle {
  id: string;
  label: string;
  promptModifier: string;
  icon: string; // Emoji or icon name
  color: string;
}

export type EditorTab = 'details' | 'edit' | 'export';
export type ExportFormat = '9:16' | '16:9';
